trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - '*'

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-22.04'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: Install Python
  - checkout: self
    path: ansible_collections/mattclay/aws
    displayName: Checkout Code
  - bash: pip install ansible-core==2.14.2rc1 --disable-pip-version-check
    displayName: Install Ansible Core
  - bash: ansible-galaxy collection install -r tests/requirements.yml -p ../../../ansible_collections
    displayName: Install Dependencies
  - bash: ansible-test sanity --docker -v --color
    displayName: Run Sanity Tests
  - bash: ansible-test integration --docker -v --color
    displayName: Run Integration Tests
  - bash: ansible-galaxy collection build
    displayName: Run Galaxy Build
