name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/mattclay/aws
      - name: Install Ansible Core
        run: pip install ansible-core==2.12.0 --disable-pip-version-check
      - name: Install Dependencies
        run: ansible-galaxy collection install -r tests/requirements.yml -p ../../../ansible_collections
      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color
